services:
  db.mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Baked.Test
      MYSQL_TCP_PORT: 3366
    ports:
      - 3366:3366
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  db.postgresql:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Baked.Test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d Baked.Test'"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  api.load-test:
  stub-api:
    build:
      dockerfile: core/test/Baked.Test.LoadTest/Dockerfile
    ports:
      - 5467:80

  api:
    build:
      dockerfile: core/test/Baked.Test.Application/Dockerfile
      args:
        ENVIRONMENT: Production
    ports:
      - 5151:80
    depends_on:
      db.mysql:
        condition: service_healthy
      db.postgresql:
        condition: service_healthy
    links:
      - db.mysql
      - db.postgresql
      - api.load-test

  ui:
    build:
      dockerfile: ui/playground/Dockerfile
    ports:
      - 3000:3000
    links:
      - api
