version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Baked.Test.Recipe.Service.Application
      MYSQL_TCP_PORT: 3366
    ports:
      - 3366:3366
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost','-P','3366', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3366
    restart: always
    ports:
      - 8080:80
  recipe.service:
    build:
      dockerfile: test/recipe/Baked.Test.Recipe.Service.Application/Dockerfile
      args:
        ENVIRONMENT: Production
    ports:
      - 5151:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
