services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Baked.Test.Recipe.Service.Application
      MYSQL_TCP_PORT: 3366
    ports:
      - 3366:3366
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  recipe.service:
    build:
      dockerfile: test/recipe/Baked.Test.Recipe.Service.Application/Dockerfile
      args:
        ENVIRONMENT: Production
    ports:
      - 5151:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
