# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.public
        - ./.theme/.temp
        - ./.theme/content
  - touch:
      path: ./.theme/.env.local

  # process and move markdowns to content
  - extractDiagrams:
      source: ./
      target: ./.theme/.temp
      config:
        backgroundColor: '#000000'
        theme: base
        outputFormat: 'svg'
        deviceScaleFactor: 1
        themeVariables:
          primaryColor: '#fa465b'
          primaryTextColor: '#fff'
          primaryBorderColor': '#7c0000'
          lineColor: '#b3b3b3'
          secondaryColor: '#000000'
          secondaryTextColor: '#b3b3b3'
          tertiaryColor: '#fff'
  - rename:
      source: ./.theme/.temp
      find: README.md
      replace: index.md
  - replaceContent:
      extension: .md
      source: ./.theme/.temp
      oldText: README.md
      newText: index.md
  - move:
      extension: .md
      source: ./.theme/.temp
      target: ./.theme/content

  # copy all assets to .public
  - copy:
      source: ./.theme/public
      target: ./.theme/.public
  - copy:
      extension: .png
      source: ./
      target: ./.theme/.public
  - move:
      extension: .svg
      source: ./.theme/.temp
      target: ./.theme/.public
