name: Publish
on:
  pull_request:
    types:
      - labeled
    branches:
      - main
jobs:
  remove-label:
    # Remove when not in release branch
    name: Remove Label
    if: github.event.label.name == 'Publish' && github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        name: Remove Publish Label
        with:
          labels: 'Publish'

  check-version:
    # Start publish when in release branch
    # This job fetches current version from Directory.Build.props and checks if this version already pushed to nuget
    name: Check Version
    if: github.event.label.name == 'Publish' && github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') == true
    runs-on: ubuntu-latest
    outputs:
      # Version number that is parsed from Directory.Build.props
      version: ${{ steps.parse.outputs.version }}
      # Flag to indicate a new version should be built or not.
      #   true means it was already published
      #   false means pack & push is required
      action: ${{ steps.check.outputs.action }}
    steps:
      - uses: actions/checkout@v3
      - name: Parse Version
        id: parse
        run: |
          # 1. cat outputs content of Directory.Build.props file to stream editor (sed)
          # 2. first sed removes all lines except with Version info
          # 3. second sed removes <Version> and </Version> and spaces
          # 4. result is only version which is set to the $version variable
          version=$(cat Directory.Build.props | sed -n '/<Version>/p' | sed '/[ <>a-zA-Z\/]/ s///g')
          # value of $version is set as a step output
          echo "version="$version >> $GITHUB_OUTPUT

  generate-docs:
    needs: check-version
    name: Generate Docs
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.check-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Docs
        run: |
          cd docs/.theme/
          npm install
          npm run generate:production
      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/.theme/.output/public
          if-no-files-found: error
  publish-docs:
    needs: generate-docs
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs branch
        uses: actions/checkout@v3
        with:
          ref: do.mouseless.codes
      - name: Remove Old Files
        run: |
          git rm -rf .
          git clean -fxd
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs
      - name: Commit & Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add -A
          git commit -m 'deploy docs v${{ needs.generate-docs.outputs.version }}'
          git push -f
