name: Remove Labels

on:
  pull_request:
    types: [synchronize]
    branches:
      - main
jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest
    steps:
      - name: Remove Publish Label
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = "Publish";
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              name: labelToRemove
            });
